services:
  rerank-service:
    build: .
    container_name: vllm-rerank-service-4B
    network_mode: bridge
    ports:
      - "30603:8000"
    environment:
      # Python 相关
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app

      # GPU 相关
      CUDA_VISIBLE_DEVICES: 0
      NVIDIA_VISIBLE_DEVICES: 0
      VLLM_WORKER_MULTIPROC_METHOD: spawn

      # 模型配置（可覆盖 Dockerfile 默认值）
      MODEL_PATH: /models/Qwen3-Reranker-4B
      MODEL_SIZE: 4B
      GPU_MEMORY_UTILIZATION: 0.7
      MAX_MODEL_LEN: 16384

      # 服务配置
      HOST: 0.0.0.0
      PORT: 8000
      LOG_LEVEL: INFO
      WORKERS: 1
    volumes:
      - /root/git_model/:/models/:ro
      - ./logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # 使用 'all' 来指定所有可用的 GPU
              capabilities: [ gpu ]
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s