version: '3.8'

services:
  rerank-service:
    build: .
    container_name: vllm-rerank-service
    ports:
      - "8888:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0  # 指定使用的GPU设备
      - MODEL_PATH=/models/Qwen3-Reranker-4B  # 模型路径
      - MODEL_SIZE=4B  # 模型大小
      - GPU_MEMORY_UTILIZATION=0.5  # GPU内存使用率
      - MAX_MODEL_LEN=32000  # 最大模型长度
    volumes:
      # 挂载本地模型目录（如果使用本地模型）
      - ${LOCAL_MODEL_PATH:-/tmp/models}:/models
      # 挂载日志目录
      - ./logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s